### PR TITLE
Writes to ssa_dev db events table for each worker call

### PR DESCRIPTION
**Pull request by martinstannard**
Adds:

* ecto for events model
* supervisor for db connection management
* writes event on each worker call

### CODE REVIEW

**Comment by martinstannard** [comment]
@lachie thoughts?

**Comment by lachie** [comment]
cool :rocket: :guitar:

**Comment by martinstannard** [comment]
@lachie - getting about 1000 insert/sec into the db now with the change above, ok?

**Comment by lachie** [comment]
Seems like a good start!

**Comment by martinstannard** [comment]
Will start deving off this repo now.

**Pull request merged**
